---
version: "2.0"
services:
  stacksrv:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: stacksrv
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8090:8090"
    environment:
      TZ: US/Pacific
      QUEUE_SIZE: 100
      CONN_POOL_SIZE: 100
      LOG_LEVEL: debug
